import { Pokemon } from './types';

export const POKEMON_DATA: Pokemon[] = [
  {
    id: '25',
    name: 'Pikachu',
    type: 'Electric',
    hp: 120,
    attack: 85,
    defense: 50,
    speed: 95,
    description: 'Generates powerful electrical storms when agitated. Loves berries.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png',
    rarity: 'Rare',
    color: 'from-yellow-400 to-yellow-600',
  },
  {
    id: '9',
    name: 'Blastoise',
    type: 'Water',
    hp: 150,
    attack: 70,
    defense: 90,
    speed: 40,
    description: 'Its shell is harder than diamond. Swims at incredible speeds.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png',
    rarity: 'Common',
    color: 'from-blue-400 to-blue-600',
  },
  {
    id: '6',
    name: 'Charizard',
    type: 'Fire',
    hp: 110,
    attack: 100,
    defense: 60,
    speed: 80,
    description: 'Born from volcanic ash. Its breath can melt steel instantly.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png',
    rarity: 'Rare',
    color: 'from-red-400 to-red-600',
  },
  {
    id: '3',
    name: 'Venusaur',
    type: 'Grass',
    hp: 130,
    attack: 75,
    defense: 75,
    speed: 60,
    description: 'Blends perfectly into forests. Attacks with razor-sharp vines.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png',
    rarity: 'Common',
    color: 'from-green-400 to-green-600',
  },
  {
    id: '150',
    name: 'Mewtwo',
    type: 'Psychic',
    hp: 90,
    attack: 110,
    defense: 40,
    speed: 100,
    description: 'Can read minds within a 1-mile radius. Levitates constantly.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png',
    rarity: 'Legendary',
    color: 'from-purple-400 to-purple-600',
  },
];