import { Pokemon } from './types';

export const POKEMON_DATA: Pokemon[] = [
  {
    id: '25',
    name: 'Pikachu',
    type: 'Electric',
    hp: 120,
    attack: 85,
    defense: 50,
    speed: 95,
    description: 'Generates powerful electrical storms when agitated. Loves berries.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png',
    rarity: 'Rare',
    color: 'from-yellow-400 to-yellow-600',
  },
  {
    id: '9',
    name: 'Blastoise',
    type: 'Water',
    hp: 150,
    attack: 70,
    defense: 90,
    speed: 40,
    description: 'Its shell is harder than diamond. Swims at incredible speeds.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png',
    rarity: 'Common',
    color: 'from-blue-400 to-blue-600',
  },
  {
    id: '6',
    name: 'Charizard',
    type: 'Fire',
    hp: 110,
    attack: 100,
    defense: 60,
    speed: 80,
    description: 'Born from volcanic ash. Its breath can melt steel instantly.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png',
    rarity: 'Rare',
    color: 'from-red-400 to-red-600',
  },
  {
    id: '3',
    name: 'Venusaur',
    type: 'Grass',
    hp: 130,
    attack: 75,
    defense: 75,
    speed: 60,
    description: 'Blends perfectly into forests. Attacks with razor-sharp vines.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png',
    rarity: 'Common',
    color: 'from-green-400 to-green-600',
  },
  {
    id: '150',
    name: 'Mewtwo',
    type: 'Psychic',
    hp: 90,
    attack: 110,
    defense: 40,
    speed: 100,
    description: 'Can read minds within a 1-mile radius. Levitates constantly.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png',
    rarity: 'Legendary',
    color: 'from-purple-400 to-purple-600',
  },
  {
    id: '1',
    name: 'Bulbasaur',
    type: 'Grass',
    hp: 90,
    attack: 60,
    defense: 60,
    speed: 50,
    description: 'A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png',
    rarity: 'Common',
    color: 'from-green-500 to-emerald-600',
  },
  {
    id: '4',
    name: 'Charmander',
    type: 'Fire',
    hp: 80,
    attack: 70,
    defense: 50,
    speed: 75,
    description: 'Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png',
    rarity: 'Common',
    color: 'from-orange-500 to-red-500',
  },
  {
    id: '7',
    name: 'Squirtle',
    type: 'Water',
    hp: 85,
    attack: 60,
    defense: 80,
    speed: 55,
    description: 'After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png',
    rarity: 'Common',
    color: 'from-cyan-500 to-blue-500',
  },
  {
    id: '94',
    name: 'Gengar',
    type: 'Ghost',
    hp: 100,
    attack: 120,
    defense: 60,
    speed: 110,
    description: 'Under a full moon, this Pokémon likes to mimic the shadows of people and laugh at their fright.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png',
    rarity: 'Rare',
    color: 'from-purple-700 to-indigo-900',
  },
  {
    id: '133',
    name: 'Eevee',
    type: 'Normal',
    hp: 80,
    attack: 55,
    defense: 50,
    speed: 55,
    description: 'Its genetic code is irregular. It may mutate if it is exposed to radiation from element stones.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png',
    rarity: 'Common',
    color: 'from-orange-200 to-amber-400',
  },
  {
    id: '143',
    name: 'Snorlax',
    type: 'Normal',
    hp: 160,
    attack: 110,
    defense: 65,
    speed: 30,
    description: 'Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/143.png',
    rarity: 'Rare',
    color: 'from-teal-700 to-slate-800',
  },
  {
    id: '149',
    name: 'Dragonite',
    type: 'Dragon',
    hp: 130,
    attack: 134,
    defense: 95,
    speed: 80,
    description: 'An extremely rarely seen marine Pokémon. Its intelligence is said to match that of humans.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/149.png',
    rarity: 'Rare',
    color: 'from-orange-300 to-orange-500',
  },
  {
    id: '249',
    name: 'Lugia',
    type: 'Psychic',
    hp: 140,
    attack: 90,
    defense: 130,
    speed: 110,
    description: 'It sleeps in a deep-sea trench. If it flaps its wings, it is said to cause a 40-day storm.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/249.png',
    rarity: 'Legendary',
    color: 'from-slate-300 to-blue-300',
  },
  {
    id: '384',
    name: 'Rayquaza',
    type: 'Dragon',
    hp: 120,
    attack: 150,
    defense: 90,
    speed: 95,
    description: 'It lives in the ozone layer far above the clouds and cannot be seen from the ground.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/384.png',
    rarity: 'Legendary',
    color: 'from-emerald-500 to-green-700',
  },
  {
    id: '448',
    name: 'Lucario',
    type: 'Fighting',
    hp: 100,
    attack: 110,
    defense: 70,
    speed: 90,
    description: 'By reading the auras of all things, it can tell how others are feeling from over half a mile away.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/448.png',
    rarity: 'Rare',
    color: 'from-blue-600 to-slate-700',
  },
  {
    id: '658',
    name: 'Greninja',
    type: 'Water',
    hp: 100,
    attack: 105,
    defense: 67,
    speed: 122,
    description: 'It creates throwing stars out of compressed water. When it spins them and throws them, they can split metal.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/658.png',
    rarity: 'Rare',
    color: 'from-blue-700 to-indigo-900',
  },
  {
    id: '282',
    name: 'Gardevoir',
    type: 'Fairy',
    hp: 100,
    attack: 125,
    defense: 65,
    speed: 80,
    description: 'To protect its Trainer, it will expend all its psychic power to create a small black hole.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/282.png',
    rarity: 'Rare',
    color: 'from-teal-300 to-emerald-500',
  },
  {
    id: '445',
    name: 'Garchomp',
    type: 'Dragon',
    hp: 120,
    attack: 130,
    defense: 95,
    speed: 102,
    description: 'When it folds up its body and extends its wings, it looks like a jet plane. It flies at sonic speed.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/445.png',
    rarity: 'Rare',
    color: 'from-indigo-600 to-blue-800',
  },
  {
    id: '248',
    name: 'Tyranitar',
    type: 'Rock',
    hp: 130,
    attack: 134,
    defense: 110,
    speed: 61,
    description: 'Its body can’t be harmed by any sort of attack, so it is very eager to make challenges against enemies.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/248.png',
    rarity: 'Rare',
    color: 'from-lime-700 to-emerald-900',
  },
  {
    id: '130',
    name: 'Gyarados',
    type: 'Water',
    hp: 130,
    attack: 125,
    defense: 79,
    speed: 81,
    description: 'Rarely seen in the wild. Huge and vicious, it is capable of destroying entire cities in a rage.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/130.png',
    rarity: 'Rare',
    color: 'from-blue-600 to-cyan-700',
  },
  {
    id: '65',
    name: 'Alakazam',
    type: 'Psychic',
    hp: 90,
    attack: 130,
    defense: 45,
    speed: 120,
    description: 'Its brain can outperform a super-computer. Its intelligence quotient is said to be 5,000.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/65.png',
    rarity: 'Rare',
    color: 'from-yellow-600 to-yellow-800',
  },
  {
    id: '59',
    name: 'Arcanine',
    type: 'Fire',
    hp: 120,
    attack: 110,
    defense: 80,
    speed: 95,
    description: 'A Pokémon that has been admired since the past for its beauty. It runs agilely as if on wings.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/59.png',
    rarity: 'Rare',
    color: 'from-orange-400 to-red-600',
  },
  {
    id: '131',
    name: 'Lapras',
    type: 'Ice',
    hp: 140,
    attack: 85,
    defense: 80,
    speed: 60,
    description: 'A gentle soul that can read the minds of people. It can ferry people across the sea on its back.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/131.png',
    rarity: 'Rare',
    color: 'from-cyan-400 to-blue-500',
  },
  {
    id: '39',
    name: 'Jigglypuff',
    type: 'Fairy',
    hp: 110,
    attack: 45,
    defense: 30,
    speed: 40,
    description: 'When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/39.png',
    rarity: 'Common',
    color: 'from-pink-300 to-pink-500',
  },
  {
    id: '68',
    name: 'Machamp',
    type: 'Fighting',
    hp: 120,
    attack: 130,
    defense: 80,
    speed: 55,
    description: 'Its four ruggedly developed arms can launch a flurry of 1,000 punches in just two seconds.',
    image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/68.png',
    rarity: 'Rare',
    color: 'from-stone-400 to-stone-600',
  },
];